nav:
  - 主页: 'index.md'
plugins:
  - search
  - markdownextradata: {}
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Spring-Society
    
theme: 
    name: material
    language: zh
    
site_name: 欧亨利的故事
repo_url: 'https://github.com/Spring-Society/O-Henry-s-Story'
repo_name: '欧亨利的故事'